apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::768693789298:role/terraform-admin
      username: terraform-admin
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::768693789298:user/terraform-admin
      username: terraform-admin
      groups:
        - system:masters