apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::768693789298:role/AmazonEKSAutoClusterRole
      username: eks-admin
      groups:
        - system:masters
    # keep existing entries if present